serverless/plugins

plugins.json
=> Remove duplicate serverless-plugin-stage-variables plugin

plugins.test.js
Test now checks if plugin which should be added is unique.
=> Add test for duplication check

plugins.json
This PR adds Jest plugin to plugin listing.
=> add jest plugin

plugins.json
Add Clojurescript plugin & fix alignment of preceding entries.
=> serverless-cljs-plugin

plugins.json
Plugin here: https://github.com/FidelLimited/serverless-plugin-select
=> Add serverless-plugin-select to list

plugins.json
Let the community know of the stop-gap
=> SQS Fifo Queues:

plugins.json
Signed-off-by: Erica Windisch <erica@iopipe.com>
=> Add IOpipe to plugins list.

README.md
Forgot to run npm run docs on the previous PR.
=> Add serverless-kms-secrets to README

README.md, plugins.json
@pmuens I would like to move the serverless-kubeless repo to Bitnami org.
=> moving the repo to bitnami org

plugins.json
The plugin is finally back for Serverless 1.x.
=> Added serverless-sentry plugin

plugins.json
howdy. found a couple errors that make this file harder to parse
=> fix redirects and remove .git extension

README.md, plugins.json
The plugin to configure the AWS api gateway: Binary support, Headers and Body template mappings
=> update plugin.json to add a new plugin

README.md, plugins.json
Updated plugin location for `serverless-webpack` and generated new README
=> Updated serverless-webpack

README.md, plugins.json
I created and published a fully-featured plugin to manage Alexa Skills with Serverless Framework.
=> Add Alexa Skills Plugin

plugins.json
Added my plugin  to pack C# lambdas functions that are spread to multiple CS projects.
=> serverless-multi-dotnet, plugin to pack C# lambdas functions that are spread to multiple CS projects.

plugins.json
The fullstack-serverless plugin creates a fullstack serverless web app with a AWS CloudFront distribution that serves static web content from S3 and routes API traffic to API Gateway.
=> Add fullstack-serverless to the list of plugins.

package-lock.json
Fixes github notification about vuln in merge package
=> recreate package-lock.json to update merge

plugins.json
⊂◉‿◉つ
Generate list of api endpoints & stack outputs for consumption in other applications + service discovery.
This will output to `.serverless/manifest.json` file.
Add to plugins array in `serverless.yml`
```yml
service: my-example-service
plugins:
- serverless-manifest-plugin
```
Outputs `urls`, `functions`, `outputs` etc.
`.serverless/manifest.json`
```json
{
"dev": {
"urls": {
"base": "https://abc-123.execute-api.us-west-1.amazonaws.com/dev",
"byPath": {
"track": {
"url": "https://abc-123.execute-api.us-west-1.amazonaws.com/dev/track",
"method": [
"post"
]
},
"identify": {
"url": "https://abc-123.execute-api.us-west-1.amazonaws.com/dev/identify",
"method": [
"post"
]
}
},
"byFunction": {
"track": {
"url": "https://abc-123.execute-api.us-west-1.amazonaws.com/dev/track",
"method": [ …
```
=> add manifest plugin

README.md
Added instructions where to find the criteria to become a community, approved or certified plugin as well as link to form to apply.
=> Added instructions to get approved

plugins.json
Adds [@vulcancreative/serverless-storage](https://www.npmjs.com/package/@vulcancreative/serverless-storage) to the `plugins.json` manifest
=> Add @vulcancreative/serverless-storage
